---
title: '**Homework 5**'
subtitle: | 
  | Eco 4306 Economic and Business Forecasting
  | Spring 2019
  | Due: Thursday, March 22, before the class
urlcolor: magenta
linkcolor: magenta
output:
  pdf_document: default
---

\renewcommand{\baselinestretch}{1.15} \selectfont

## **Problem 1** 

Obtain monthly data for change, in millions of dollars, in Total Private Residential Construction Spending, for the period 1993M01-2017M12. This data is available under code [`PRRESCON`](https://fred.stlouisfed.org/series/PRRESCON) on FRED. Note that you either need to switch the units to "Change, Millions of Dollars" on FRED, or construct the change in EViews yourself by calculating the first differences `DCONST = CONST - CONST(-1)`.

(a) Import the data for 1993M01-2017M12 into EViews, then change your sample to 1993M01-2013M12. Use this data to create time series plot and correlogram similar to the two panels in Figure 7.19 but for 1993M01-2013M12 instead of 2002M01-2011M01. 

(b) Compare your correlogram in (a) with that in Figure 7.19. Does the change in U.S. residential construction in 1993M01-2013M12 follow a similar process as in 2002M01-2011M01?

(c) Estimate a suitable multiplicative AR($p$)+S-AR($P$) model for the period 1993M01-2013M12. Create a time series plot with residuals and the correlogram for residuals. If based of these two plots the residuals do not appear to be white noise, modify your model appropriately. Report only the  estimation results, residuals plot and correlogram for the final model you select. Explain why you selected that particular model over possible alternatives.

(d) Create a multistep forecast for period 2014M01-2017M12. Also generate the standard errors for this forecast to construct the lower and upper bounds of the 95\% confidence interval. Plot the actual data together with the forecast and its 95% confidence interval. Report the RMSE for this forecast. 

(e) Create a sequence of one step ahead forecasts for period 2014M01-2017M12 using fixed forecasting scheme. Also generate the standard errors for this forecast to construct the lower and upper bounds of the 95\% confidence interval. Plot the actual data together with the forecast and its 95% confidence interval. Report the RMSE for this forecast. 

(f) Comment on the difference in RMSE and the width of the confidence intervals between (d) and (e) .


<!--
\newpage

## **Problem 2** 

Download the workfile in [hpSF.zip](http://myweb.ttu.edu/jduras/files/teaching/e4306/hpSF.zip) which contain the quarterly data for House Price Index for San Francisco MSAD, code `ATNHPIUS41884Q` on [fred.stlouisfed.org](https://fred.stlouisfed.org).

Obtain the quarterly data for House Price Index for San Francisco MSAD available under code `ATNHPIUS41884Q` on [fred.stlouisfed.org](https://fred.stlouisfed.org) and under `FRED/ATNHPIUS41884Q` on [www.quandl.com](https://www.quandl.com).

(a) Construct time series for the percentage change, use it to create time series plots for the index itself and its quarterly growth rate, and the histogram for th growth rate as in Figure 8.1, but for San Francisco in 1975Q3-2016Q4 instead of San Diego MSA during 2075Q1-2008Q3.

(b) Change the sample to 1975Q3-2008Q4, plot the correlogram for the growth rate during this period.

(c) Use the results from (b) to determined the order of the AR($p$) model, and estimae it.

(d) Suppose that we use quadratic loss function. Construct the following four forecasts for period 2009Q1-2016Q4
    - multistep forecast using the AR($p) model
    - sequence of one step ahead forecasts using fixed scheme using the AR($p) model
    - sequence of one step ahead forecasts using naive forecast $f^{naive}_{t+1|t} = y_t$
    - sequence of one step ahead forecasts using simple moving average forecast $f^{MA}_{t+1|t} = 1/4( y_t + y_{t-1} + y_{t-2} + y_{y-3})$


(a) Create time series plots for the house price index `ihpsf`, and its growth rate `ghpsf`, and also the histogram for the growth rate as in Figure 8.1, but for San Francisco in 1975Q3-2016Q4 instead of San Diego MSA during 2075Q1-2008Q3. Is the growth rate weakly stationary? Is it normally distributed?

(b) Consider four forecasts for the growth in the house price index `ghpsf` during 2009Q1-2016Q4:
1. `ghpsf_f_ar_mul`: multistep forecast using an AR($p$) model
2. `ghpsf_f_ar_fix`: sequence of one step ahead forecasts using fixed scheme using the AR($p$) model
3. `ghpsf_f_naive`: sequence of one step ahead forecasts using naive forecast $f^{naive}_{t+1|t} = y_t$
4. `ghpsf_f_ma`: sequence of one step ahead forecasts using simple four observation moving average forecast $f^{MA}_{t+1|t} = 1/4( y_t + y_{t-1} + y_{t-2} + y_{y-3})$

    Create a plot with these four forecasts and the actual growth in the house price index.
    
(c) Suppose that we have symmetric quadratic loss function $L(e)=e^2$. For each of these four forecasts $k=1,2,3,4$, construct the forecast errors $e_{t+j,1}^{(k)}$, their squares $(e_{t+j,1}^{(k)})^2$, and use them calculate the sample MSE loss $\bar L = \frac{1}{T-t}\sum_{j=0}^{T-t-1} (e_{t+j,1}^{(k)})^2$. Rank the forecasts based on the MSE; which forecast is the best and which the worst?

(d) The one step ahead forecast error for optimal forecasts should be white noise - there should not be any linear dependence. Plot the correlograms for forecasts $k=2,3,4$. Do they satisfy this property?

(e) Perform the test of equal predictive ability for fixed scheme forecast, $k=2$, vs naive forecast, $k=3$: first construct the differences in the squared errors $\Delta L_{t,1} = L(e_{t,1}^{(3)}) - L(e_{t,1}^{(2)}) = (e_{t,1}^{(3)})^2 - (e_{t,1}^{(2)})^2$, run the regression
$$
    \Delta L_{t+j,1} = \beta_0 + u_{t+j}    \quad \text{ with } j=0,1,2,\ldots,T-t-1
$$
and determine whether the estimated coefficient $\hat \beta_0$ is statistically significant. Comment on the results.
    
(f) Perform the test of equal predictive ability for fixed scheme forecast, $k=2$, vs  moving average forecast, $k=4$ following similar steps as in (e). Comment on the results.

-->
